version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: airline-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - airline-network

  frontend:
    build:
      context: ./frontend
    container_name: airline-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - airline-network

networks:
  airline-network:
    driver: bridge
